# Generated by Django 4.2.10 on 2024-02-19 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(choices=[('SUMMER', 'SUMMER'), ('WINTER', 'WINTER'), ('SPORTS', 'SPORTS')], max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('INDOOR', 'INDOOR'), ('OUTDOOR', 'OUTDOOR')], max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='app.tag')),
            ],
        ),
    ]
