# Generated by Django 4.2.10 on 2024-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(choices=[('SUMMER', 'SUMMER'), ('WINTER', 'WINTER'), ('SPORTS', 'SPORTS')], max_length=100, unique=True),
        ),
    ]
